apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment4
  namespace: my-namespace
  labels:
    app: myapp4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp4
  template:
    metadata:
      labels:
        app: myapp4
    spec:
      containers:
        - name: myapp4
          image: alexkkk21/nextjsapp4
          ports:
            - containerPort: 8889

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-service
# spec:
#   selector:
#     app: myapp
#   ports:
#     - protocol: TCP
#       port: 9977
#       targetPort: 8889

---
apiVersion: v1
kind: Service
metadata:
  name: myapp4-service
  namespace: my-namespace
spec:
  selector:
    app: myapp4
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
      nodePort: 30004
