name: CI for project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # REGISTRY: docker.io             # или docker.io для Docker Hub
  IMAGE_NAME: nextjsapp3  # owner/repo
  REGITRY_USER: alexkkk21  # owner/repo
  REGISTRY: ghcr.io  # owner/repo

jobs:
  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm i

    - name: Run tests
      run: npm run lint

    # - name: Extract metadata for the Docker image
    #   id: meta
    #   uses: docker/metadata-action@v5
    #   with:
    #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #     tags: |
    #       type=raw,value=latest,enable={{is_default_branch}}
    #       type=sha,prefix={{branch}}-,suffix=-{{date 'X'}}

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildxx
    #   uses: docker/setup-buildx-action@v3

    # - name: Log in to Container registry
    #   uses: docker/login-action@v3
    #   with:
    #     # registry: ${{ env.REGISTRY }}
    #     username: ${{ env.REGITRY_USER }}
    #     password: ${{ secrets.DOCKER_PASSWORD  }}

    - name: Login to docker hub
      run: echo ${{ secrets.DC_TOKEN  }} | docker login --username alexkkk21 --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }} .

    - name: Tag Docker image
      run: docker tag ${{ env.IMAGE_NAME }} alexkkk21/${{ env.IMAGE_NAME }}

    - name: Push Docker image
      run: docker push alexkkk21/${{ env.IMAGE_NAME }}
