name: CI for project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: hub.docker.com             # или docker.io для Docker Hub
  IMAGE_NAME: ${{ github.repository }}  # owner/repo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm i

      - name: Run tests
        run: npm run lint

