name: CI for project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # REGISTRY: docker.io             # или docker.io для Docker Hub
  IMAGE_NAME: "nextjsapp3"  # owner/repo
  REGITRY_USER: "alexkkk21"  # owner/repo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm i

      - name: Run tests
        run: npm run lint

  build_image1:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          # registry: ${{ env.REGISTRY }}
          username: ${{ env.REGITRY_USER }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

      # - name: Extract metadata for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #      images: |
      #       name/app

      #      tags: |
      #       type=schedule
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=semver,pattern={{major}}
      #       type=sha

  build_image2:
    needs: build_image1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # push: true
          tags: ${{ env.REGITRY_USER }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}  
